export const MIN_LENGTH_INPUT_STRING = 3;
export const MAX_LENGTH_INPUT_STRING = 30;
export const MAX_LENGTH_INPUT_TITLE_CARD = 120;
export const MIN_LENGTH_PASSWORD = 8;
export const MAX_LENGTH_PASSWORD = 256;
export const MAX_TITLE_LENGTH = 20;
export const WIDTH_KANBAN_COLUMN = 350;
export const WIDTH_GAP_BETWEEN_COLUMN = 16;
